export const products = [
  {
    id: 1,
    name: "Product 1",
    price: 99.99,
    image: "/product1.jpg",
    discountPercentage: 10,
    rating: 4.5,
    category: "Electronics",
  },
  {
    id: 2,
    name: "Product 2",
    price: 79.99,
    image: "/product2.jpg",
    discountPercentage: 5,
    rating: 4.0,
    category: "Fashion",
  },
  {
    id: 3,
    name: "Product 3",
    price: 49.99,
    image: "/product3.jpg",
    discountPercentage: 0,
    rating: 3.5,
    category: "Furniture",
  },
  {
    id: 4,
    name: "Product 4",
    price: 99.99,
    image: "/product4.jpg",
    discountPercentage: 15,
    rating: 4.8,
    category: "Books",
  },
  {
    id: 5,
    name: "Product 5",
    price: 79.99,
    image: "/product5.jpg",
    discountPercentage: 20,
    rating: 4.2,
    category: "Groceries",
  },
  {
    id: 6,
    name: "Product 6",
    price: 49.99,
    image: "/product6.jpg",
    discountPercentage: 10,
    rating: 3.9,
    category: "Appliances",
  },
];
